package com.skoev.onlinestore.entities.order;

import java.util.*;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import javax.persistence.Temporal; 
import javax.persistence.TemporalType; 
import javax.persistence.Enumerated; 
import javax.persistence.EnumType;
import java.text.*;

/**
 * This class represents the status of an order in more detail than 
 * {@link OrderStatusEnum}. It includes not only the order's processing status
 * (i.e. {@link OrderStatusEnum}), but also the date the order was placed in that
 * status and the user that placed it in that status. 
 */
@Entity @Table(name="ORDER_STATUSES")
public class OrderStatusEntity implements Serializable {
   /**
     * Autogenerated ID value.
     */
   @GeneratedValue
   @Id
   private Long id; 
   @Enumerated(EnumType.STRING)
   private OrderStatusEnum status; 
   @Temporal(TemporalType.TIMESTAMP)
   private Date statusBegan; 
   /**
    * Username of user who put the order in this status.
    */
   private String actor; 
   //@ManyToOne
   //private UserEntity actor;

    public String getActor() {
        return actor;
    }

    public Long getId() {
        return id;
    }

    public OrderStatusEnum getStatus() {
        return status;
    }

    public Date getStatusBegan() {
        return statusBegan;
    }

    public void setActor(String actor) {
        this.actor = actor;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setStatus(OrderStatusEnum status) {
        this.status = status;
    }

    public void setStatusBegan(Date statusBegan) {
        this.statusBegan = statusBegan;
    }
   
    public String getStatusBeganFormatted(){
    DateFormat dateFormat = DateFormat.getDateTimeInstance(DateFormat.SHORT, DateFormat.SHORT, Locale.US);
        dateFormat.setTimeZone(TimeZone.getTimeZone("America/New_York"));
        return dateFormat.format(statusBegan); 
        
    }
   
   
   
}
