package com.skoev.onlinestore.entities.product;

import javax.persistence.*;

/**
 * This class represents the image of a product in the online store. The image
 * file is saved in the database as a BLOB.  
 */
@Entity
@Table(name = "IMAGES")
public class ImageEntity {
    /**
     * Autogenerated ID
     */
    @GeneratedValue
    @Id
    private Long imageID;
    /**
     * Name of the image; for example it could be "Book cover" or "CD tracklist". 
     * 
     */
    private String imageName;
    /**
     * Name of the image file, including the extension (for example, bookcover.jpg)
     */
    private String fileName;
    /**
     * Length of the image file in bytes
     */
    private Long fileLength;
    /**
     * Content of the image file. 
     */
    @Lob
    @Basic(fetch = FetchType.LAZY)
    private byte[] content;

    public byte[] getContent() {
        return content;
    }

    public Long getFileLength() {
        return fileLength;
    }

    public String getFileName() {
        return fileName;
    }

    public Long getImageID() {
        return imageID;
    }

    public String getImageName() {
        return imageName;
    }

    public void setContent(byte[] content) {
        this.content = content;
    }

    public void setFileLength(Long fileLength) {
        this.fileLength = fileLength;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public void setImageID(Long imageID) {
        this.imageID = imageID;
    }

    public void setImageName(String imageName) {
        this.imageName = imageName;
    }
}
